name: Release
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '16.15.0'
      - name: Install
        run: npm install --force
      - name: Semantic Release
        uses: wow-actions/release-github-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}